import Navbar from "@/components/navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
  Box,
  Button,
  ChakraProvider,
  ColorModeScript,
  Container,
  Flex,
  Grid,
  HStack,
  Icon,
  SimpleGrid,
  Stack,
} from "@chakra-ui/react";
import { Providers } from "./providers";
import { theme } from "@/theme";
import { Icons } from "@/components/icons";
import { ButtonBack } from "@/components/logic/button-back";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ColorModeScript
          initialColorMode={theme.config.initialColorMode}
        />
        <Providers>
          <Container maxW="container.lg" h="full">
            <HStack justify={"center"}>
              {/* <ButtonBack /> */}

              <Box>
                <Navbar />
              </Box>
            </HStack>
            {children}
          </Container>
        </Providers>
      </body>
    </html>
  );
}
